// <auto-generated />
namespace MMTRShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "202301160235047_RenameEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
