namespace MMTRShopWPF.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FixAutoKey : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Admins", "UserId", "dbo.Users");
            DropForeignKey("dbo.Clients", "UserId", "dbo.Users");
            DropForeignKey("dbo.Operators", "UserId", "dbo.Users");
            DropForeignKey("dbo.BankCards", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Carts", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Orders", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Feedbacks", "Client_Id", "dbo.Clients");
            DropForeignKey("dbo.Favourites", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Carts", "ProductId", "dbo.Products");
            DropForeignKey("dbo.OrderContents", "ProductId", "dbo.Products");
            DropForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Favourites", "ProductId", "dbo.Products");
            DropForeignKey("dbo.Products", "BrandId", "dbo.Brands");
            DropForeignKey("dbo.Products", "CategoryId", "dbo.Categories");
            DropForeignKey("dbo.OrderContents", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Orders", "StatusId", "dbo.Status");
            DropPrimaryKey("dbo.Admins");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.BankCards");
            DropPrimaryKey("dbo.Clients");
            DropPrimaryKey("dbo.Carts");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.Brands");
            DropPrimaryKey("dbo.Categories");
            DropPrimaryKey("dbo.OrderContents");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Status");
            DropPrimaryKey("dbo.Feedbacks");
            DropPrimaryKey("dbo.Favourites");
            DropPrimaryKey("dbo.Operators");
            AlterColumn("dbo.Admins", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Users", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.BankCards", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Clients", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Carts", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Products", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Brands", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Categories", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.OrderContents", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Orders", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Status", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Feedbacks", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Favourites", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Operators", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AddPrimaryKey("dbo.Admins", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.BankCards", "Id");
            AddPrimaryKey("dbo.Clients", "Id");
            AddPrimaryKey("dbo.Carts", "Id");
            AddPrimaryKey("dbo.Products", "Id");
            AddPrimaryKey("dbo.Brands", "Id");
            AddPrimaryKey("dbo.Categories", "Id");
            AddPrimaryKey("dbo.OrderContents", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Status", "Id");
            AddPrimaryKey("dbo.Feedbacks", "Id");
            AddPrimaryKey("dbo.Favourites", "Id");
            AddPrimaryKey("dbo.Operators", "Id");
            AddForeignKey("dbo.Admins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Clients", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Operators", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BankCards", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "Client_Id", "dbo.Clients", "Id");
            AddForeignKey("dbo.Favourites", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderContents", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Favourites", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "BrandId", "dbo.Brands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "CategoryId", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderContents", "OrderId", "dbo.Orders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Orders", "StatusId", "dbo.Status");
            DropForeignKey("dbo.OrderContents", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Products", "CategoryId", "dbo.Categories");
            DropForeignKey("dbo.Products", "BrandId", "dbo.Brands");
            DropForeignKey("dbo.Favourites", "ProductId", "dbo.Products");
            DropForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products");
            DropForeignKey("dbo.OrderContents", "ProductId", "dbo.Products");
            DropForeignKey("dbo.Carts", "ProductId", "dbo.Products");
            DropForeignKey("dbo.Favourites", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Feedbacks", "Client_Id", "dbo.Clients");
            DropForeignKey("dbo.Orders", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Carts", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.BankCards", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Operators", "UserId", "dbo.Users");
            DropForeignKey("dbo.Clients", "UserId", "dbo.Users");
            DropForeignKey("dbo.Admins", "UserId", "dbo.Users");
            DropPrimaryKey("dbo.Operators");
            DropPrimaryKey("dbo.Favourites");
            DropPrimaryKey("dbo.Feedbacks");
            DropPrimaryKey("dbo.Status");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.OrderContents");
            DropPrimaryKey("dbo.Categories");
            DropPrimaryKey("dbo.Brands");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.Carts");
            DropPrimaryKey("dbo.Clients");
            DropPrimaryKey("dbo.BankCards");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Admins");
            AlterColumn("dbo.Operators", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Favourites", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Feedbacks", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Status", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.OrderContents", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Categories", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Brands", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Products", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Carts", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Clients", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.BankCards", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Users", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Admins", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Operators", "Id");
            AddPrimaryKey("dbo.Favourites", "Id");
            AddPrimaryKey("dbo.Feedbacks", "Id");
            AddPrimaryKey("dbo.Status", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.OrderContents", "Id");
            AddPrimaryKey("dbo.Categories", "Id");
            AddPrimaryKey("dbo.Brands", "Id");
            AddPrimaryKey("dbo.Products", "Id");
            AddPrimaryKey("dbo.Carts", "Id");
            AddPrimaryKey("dbo.Clients", "Id");
            AddPrimaryKey("dbo.BankCards", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.Admins", "Id");
            AddForeignKey("dbo.Orders", "StatusId", "dbo.Status", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderContents", "OrderId", "dbo.Orders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "CategoryId", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "BrandId", "dbo.Brands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Favourites", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderContents", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "ProductId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Favourites", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "Client_Id", "dbo.Clients", "Id");
            AddForeignKey("dbo.Orders", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Carts", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BankCards", "ClientId", "dbo.Clients", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Operators", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Clients", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Admins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
        }
    }
}
